{{- $fullName := include "kruize.fullname" . -}}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $fullName }}-db-pv-volume-{{ .Release.Namespace }}
  labels:
    type: local
    app: {{ $fullName }}-db
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}

spec:
  storageClassName: {{ .Values.db.pvc.storageClass | quote }}
  capacity:
    storage: {{ .Values.db.pvc.storageSize | quote }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ printf "%s/%s-%s" .Values.db.pvc.hostPath $fullName .Release.Namespace | quote }}
